## Numpy Array Operations

In [1]:
import numpy as np

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:",arr[2:7])
print("Slicing with step:",arr[1:8:2])
print("Negative Indexing:",arr[-5])

Basic Slicing: [3 4 5 6 7]
Slicing with step: [2 4 6 8]
Negative Indexing: 6


## Indexing and Sorting

In [17]:
arr_2d=np.array([
  [3,2,1],
  [1,5,6],
  [9,7,8],
])
print("Specific Element:",arr_2d[1,0])
print("Entire Row:",arr_2d[1])
print("Entire Column:",arr_2d[:,1])
print("Sorted Array:",np.sort(arr_2d))
print("\nSorted by column:\n",np.sort(arr_2d,axis=0))

unsorted=np.array([1,7,3,6,2,5,4])
print("\nOriginal Array:",unsorted)
print("Sorted Array:",np.sort(unsorted))  

Specific Element: 1
Entire Row: [1 5 6]
Entire Column: [2 5 7]
Sorted Array: [[1 2 3]
 [1 5 6]
 [7 8 9]]

Sorted by column:
 [[1 2 1]
 [3 5 6]
 [9 7 8]]

Original Array: [1 7 3 6 2 5 4]
Sorted Array: [1 2 3 4 5 6 7]


## Filtering Arrays

In [14]:
numbers=np.array([10,25,30,45,50])

even_numbers=numbers[numbers%2==0]
print("Even Numbers:",even_numbers)

mask=numbers>30
print("Numbers greater than 30:",numbers[mask])

Even Numbers: [10 30 50]
Numbers greater than 30: [45 50]


## Fancy Indexing vs np.where()

In [20]:
indices=[0,2,4]
print("Fancy Indexing:",numbers[indices])

where_result=np.where(numbers>30)
print("np.where() result:",numbers[where_result])

Fancy Indexing: [10 30 50]
np.where() result: [45 50]


In [25]:
condition_array=np.where(numbers>30,numbers*2,numbers)
print("Condition Array:",condition_array)

Condition Array: [ 10  25  30  90 100]


## Adding and Removing Data

In [33]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print("Combined Array:",combined)

arr = np.array([1, 2, 3, 4, 5])
deleted=np.delete(arr,2)
print("Array after deletion:",deleted)

Combined Array: [1 2 3 4 5 6]
Array after deletion: [1 2 4 5]


In [34]:
original=np.array([[1,2,3],[4,5,6]])
new_row=np.array([7,8,9])

with_new_row=np.vstack((original,new_row))
print("Array with new row:\n",with_new_row)

new_column=np.array([[10],[11]])
with_new_column=np.hstack((original,new_column))
print("Array with new column:\n",with_new_column)

Array with new row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with new column:
 [[ 1  2  3 10]
 [ 4  5  6 11]]


## Array Compatibility

In [28]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("Compatibility shapes:",a.shape==b.shape)

Compatibility shapes: True
