## Numpy array basics 

In [9]:
import numpy as np
import time

## Creating array from list

In [10]:
arr_1d=np.array([1,2,3,4,5])
print("1D_Array:",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D_Array:",arr_2d)

1D_Array: [1 2 3 4 5]
2D_Array: [[1 2 3]
 [4 5 6]]


## List vs Numpy array

In [11]:
py_list=[1,2,3,4,5]
print("Python list multiplication: ",py_list*2)

np_array=np.array([1,2,3,4,5])
print("Python numpy array multiplication: ",np_array*2)

start=time.time()
py_list=[1*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time: ",time.time()-start)

Python list multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python numpy array multiplication:  [ 2  4  6  8 10]

 List operation time:  0.12676310539245605

 Numpy operation time:  0.02469944953918457


## Creating array from scratch

In [18]:
zeros=np.zeros((3,4))
print("Zeros Array:\n",zeros)

ones=np.ones((3,4))
print("Ones Array:\n",ones)

full=np.full((2,2),7)
print("Full Array:\n",full)

random=np.random.random((2,3))
print("Random Array:\n",random)

sequence=np.arange(0,10,2)
print("Sequence Array:\n",sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.88468779 0.74546154 0.85700602]
 [0.93626913 0.60379895 0.37250065]]
Sequence Array:
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [24]:
vector=np.array([1,2,3])
print("Vector:",vector)

matrix=np.array([[1,2,3]
                 ,[4,5,6]
])
print("\nMatrix:\n",matrix)

tensor=np.array([
                 [[1,2],[3,4]],
                 [[5,6],[7,8]]
                ])
print("\nTensor:\n",tensor)

Vector: [1 2 3]

Matrix:
 [[1 2 3]
 [4 5 6]]

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [26]:
arr=np.array([[1,2,3],
             [4,5,6]])
print("Array shape:",arr.shape)
print("Array dimensions:",arr.ndim)
print("Array size:",arr.size)
print("Array data type:",arr.dtype)

Array shape: (2, 3)
Array dimensions: 2
Array size: 6
Array data type: int64


## Array Reshaping

In [32]:
arr=np.arange(12)
print("Original Array:", arr)

reshaped=arr.reshape(3,4)
print("\nReshaped Array:\n", reshaped)

flattened=reshaped.flatten()
print("\n Flattened Array:",flattened)

raveled=reshaped.ravel()
print("\n Raveled Array:",raveled)

# Transpose the array

transposed=reshaped.T
print("\n Teansposed Array:\n",transposed)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Teansposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
